name: HTTP POST on Push

on:
  push:
    branches:
      - main

jobs:
  make_http_post_request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # This step checks out your repository under $GITHUB_WORKSPACE
    - name: HTTP Request Action
      uses: fjogeleit/http-request-action@master
      with:
        url: "https://codekatabattle.it:8443/api/battles/commit" # Replace with IPADDRESS and PORT of CKB Server
        method: "POST"
        data: >
          {
            "commitHash": "${{ github.sha }}",
            "repositoryUrl": "${{ github.repository }}"
          }
        customHeaders: '{"Authorization": "Bearer ${{ secrets.JWT_TOKEN }}", "Content-Type": "application/json"}'
